@DebtQuerySystem.Api_HostAddress = http://localhost:5241/api/v1

GET {{DebtQuerySystem.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DebtQuerySystem.Api_HostAddress}}/debitos/89405361260
Accept: application/json

###

GET {{DebtQuerySystem.Api_HostAddress}}/debitos/41935789876
Accept: application/json

###

GET {{DebtQuerySystem.Api_HostAddress}}/debitos/14769238509
Accept: application/json

###